### ISSUE TITLE
Adding non-OSU curated pathways for rice

### ISSUE THREAD

**Issue by jaiswalp** [PlantReactome/pathways#2]
Justin please provide a list of such pathways

**Comment by preecej** [comment]
Everything in the "Cellular processes" branch of the pathway hierarchy is currently projected from human, and thus "curated" in the Reactome project:
http://plantreactome.gramene.org/PathwayBrowser/#/R-OSA-2894886

Other than this, OSU has performed all of the rice pathway curation.
